#!/bin/csh
set i='image.qasm'
set t = `echo $i | sed "s/.qasm//"`
set SPTH='../../Desktop/test/qasm2circ-v1.4'
echo $SPTH
cd $SPTH
python qasm2tex.py $i >! $t.tex
if (-z $t.tex) then
   echo "error in qasm2tex on $t.tex! aborting."
else
   latex $t
   dvips -D2400 -E -o $t.eps $t
   epstopdf $t.eps
endif
